# Generated by Django 5.0.3 on 2024-05-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
    ]
