# Generated by Django 5.0.3 on 2024-06-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='stadiums.stadium'),
        ),
    ]
