# Generated by Django 5.0.3 on 2024-06-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0002_alter_hall_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadiums.stadium'),
        ),
    ]
