# Generated by Django 5.0.3 on 2024-05-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='begin',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, to='images.image'),
        ),
    ]
