# Generated by Django 5.0.3 on 2024-06-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_date',
            field=models.DateField(default='1975-01-01'),
            preserve_default=False,
        ),
    ]
