# Generated by Django 5.0.3 on 2024-05-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('halls', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.hall'),
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(to='images.image'),
        ),
    ]
