# Generated by Django 5.0.3 on 2024-06-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_application_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
