# Generated by Django 5.0.3 on 2024-05-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seats.seat'),
        ),
        migrations.AddField(
            model_name='application',
            name='seats',
            field=models.ManyToManyField(through='applications.ApplicationSeat', to='seats.seat'),
        ),
    ]
