# Generated by Django 5.0.3 on 2024-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission_application_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
