# Generated by Django 5.0.3 on 2024-05-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadiums.stadium'),
        ),
    ]
