# Generated by Django 5.0.3 on 2024-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('permission_lounge', models.CharField(max_length=50)),
                ('permission_seat', models.CharField(max_length=50)),
                ('permission_application', models.CharField(max_length=50)),
                ('permission_event', models.CharField(max_length=50)),
                ('permission_ticket', models.CharField(max_length=50)),
            ],
        ),
    ]
