# Generated by Django 5.0.3 on 2024-05-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permission_lounge',
            new_name='permission_hall',
        ),
        migrations.AddField(
            model_name='role',
            name='permission_staduum',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='permission_user',
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
    ]
