# Generated by Django 5.0.3 on 2024-07-18 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_application_ticket_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0), null=True),
        ),
    ]
