# Generated by Django 5.0.3 on 2024-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
